"""
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

from helper import *

def p44():

	n = 1
	pentagonals = set()

	while True:

		n += 1
		s = pentagonal(n)

		for i in pentagonals:

			if s-i in pentagonals and abs(s-2*i) in pentagonals:

				return abs(s-2*i)

		pentagonals.add(s)

if __name__ == "__main__":

	print("Problem 44: %d" % p44())
